# This Docker Cloud Stack file is provided for reference.
# This Stack file contains both the Nginx Ghost Stack (https://github.com/donovanmuller/nginx-ghost-stack)
# as well as the Ghost stack for the my-ghost-theme Ghost image.
ghost-nginx-proxy-config:
  image: donovanmuller/nginx-ghost-proxy-template:1
  command: echo "Ghost Nginx proxy configuration volume"
  autoredeploy: false

letsencrypt-certs:
  image: busybox
  volumes:
    - "/etc/nginx/certs"
  command: echo "Letsencrypt certificate volume"
  autoredeploy: false

nginx-proxy:
  image: nginx:1
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - letsencrypt-certs
    - ghost-nginx-proxy-config

nginx-gen:
  image: donovanmuller/nginx-gen-docker-cloud:1
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  volumes_from:
    - nginx-proxy
    - ghost-nginx-proxy-config
  entrypoint: /usr/local/bin/docker-gen -notify-output -notify "./restart_service.sh" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  environment:
    - NGINX_PROXY_SERVICE_ENV_VAR=nginx-proxy
  roles:
   - global

letsencrypt-nginx-proxy:
  image: donovanmuller/docker-letsencrypt-nginx-proxy-companion:latest
  volumes_from:
    - letsencrypt-certs
    - nginx-proxy
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
  roles:
   - global
